# Generated by Django 5.2 on 2025-07-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetraining',
            name='status',
            field=models.CharField(choices=[('Inscrit', 'Inscrit'), ('En Cours', 'En Cours'), ('Attente validation manager', 'Attente validation manager'), ('Terminé', 'Terminé'), ('Annulé', 'Annulé')], default='Inscrit', max_length=100, verbose_name='Statut'),
        ),
    ]
