# Generated by Django 5.2 on 2025-08-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_training', '0002_alter_employeetraining_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedtraining',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Refusée', 'Refusée'), ('Inscrite', 'Inscrite'), ('Terminée', 'Terminée')], default='En attente', max_length=20, verbose_name='Statut de la Recommandation'),
        ),
    ]
