# Generated by Django 5.2 on 2025-08-20 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options'),
        ('performance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'Objectif")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description Détaillée')),
                ('start_date', models.DateField(verbose_name='Date de Début')),
                ('end_date', models.DateField(verbose_name='Date de Fin Cible')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Non Démarré'), ('IN_PROGRESS', 'En Cours'), ('COMPLETED', 'Complété'), ('OVERDUE', 'En Retard'), ('CANCELED', 'Annulé')], default='NOT_STARTED', max_length=20, verbose_name="Statut de l'Objectif")),
                ('target_value', models.FloatField(blank=True, null=True, verbose_name='Valeur Cible')),
                ('current_value', models.FloatField(blank=True, null=True, verbose_name='Valeur Actuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Dernière Mise à Jour')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_department', to='employee.department', verbose_name='departement Cible')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goaldepartment_set', to=settings.AUTH_USER_MODEL, verbose_name='Défini par')),
            ],
            options={
                'verbose_name': 'Objectif',
                'verbose_name_plural': 'Objectifs',
                'ordering': ['-end_date'],
            },
        ),
    ]
