# Generated by Django 5.2 on 2025-08-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0002_goaldepartement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goaldepartement',
            old_name='departement',
            new_name='department',
        ),
    ]
