# Generated by Django 5.2 on 2025-08-25 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_rename_departement_goaldepartement_department'),
        ('skill_training', '0003_alter_recommendedtraining_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancereview',
            name='next_steps',
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='overall_score',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='collaboration_equipe',
            field=models.IntegerField(choices=[(1, 'Insuffisant (Ne répond pas aux attentes)'), (2, 'À Améliorer (Répond parfois aux attentes)'), (3, 'Satisfaisant (Répond aux attentes)'), (4, 'Bon (Dépasse les attentes)'), (5, 'Excellent (Dépasse largement les attentes)')], default=1, verbose_name='Collaboration en Équipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='competences_techniques',
            field=models.IntegerField(choices=[(1, 'Insuffisant (Ne répond pas aux attentes)'), (2, 'À Améliorer (Répond parfois aux attentes)'), (3, 'Satisfaisant (Répond aux attentes)'), (4, 'Bon (Dépasse les attentes)'), (5, 'Excellent (Dépasse largement les attentes)')], default=1, verbose_name='Compétences Techniques'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='efficacite_operationnelle',
            field=models.IntegerField(choices=[(1, 'Insuffisant (Ne répond pas aux attentes)'), (2, 'À Améliorer (Répond parfois aux attentes)'), (3, 'Satisfaisant (Répond aux attentes)'), (4, 'Bon (Dépasse les attentes)'), (5, 'Excellent (Dépasse largement les attentes)')], default=1, verbose_name='Efficacité Opérationnelle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='formations_recommender',
            field=models.ManyToManyField(blank=True, null=True, to='skill_training.trainingcourse', verbose_name='Formation recommender'),
        ),
        migrations.AddField(
            model_name='performancereview',
            name='qualite_service_client',
            field=models.IntegerField(choices=[(1, 'Insuffisant (Ne répond pas aux attentes)'), (2, 'À Améliorer (Répond parfois aux attentes)'), (3, 'Satisfaisant (Répond aux attentes)'), (4, 'Bon (Dépasse les attentes)'), (5, 'Excellent (Dépasse largement les attentes)')], default=1, verbose_name='Qualité du Service Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancereview',
            name='securite_au_travail',
            field=models.IntegerField(choices=[(1, 'Insuffisant (Ne répond pas aux attentes)'), (2, 'À Améliorer (Répond parfois aux attentes)'), (3, 'Satisfaisant (Répond aux attentes)'), (4, 'Bon (Dépasse les attentes)'), (5, 'Excellent (Dépasse largement les attentes)')], default=2, verbose_name='Sécurité au Travail'),
            preserve_default=False,
        ),
    ]
