# Generated by Django 5.2 on 2025-08-25 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_remove_performancereview_next_steps_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(choices=[('Efficacité Opérationnelle', 'Efficacité Opérationnelle'), ('Qualité du Service Client', 'Qualité du Service Client'), ('Collaboration en Équipe', 'Collaboration en Équipe'), ('Sécurité au Travail', 'Sécurité au Travail'), ('Compétences Techniques', 'Compétences Techniques')], max_length=100, verbose_name='Domaine')),
                ('objectif', models.TextField(verbose_name='Objectif')),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('create_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
