# Generated by Django 5.2 on 2025-08-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Est Administrateur'),
        ),
    ]
