# Generated by Django 5.2 on 2025-08-20 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Utilisateur du systeme', 'verbose_name_plural': 'Utilisateurs du systeme'},
        ),
    ]
