# Generated by Django 5.2 on 2025-08-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bloquer',
            field=models.BooleanField(default=False, verbose_name="Cochez cette case pour bloquer l'utilisateur"),
        ),
    ]
